<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/config/bootstrap.php';

use App\Controller\AdminController;
use App\Controller\AuthController;
use App\Controller\CookbookController;
use App\Controller\HomeController;
use App\Controller\ModerationController;
use App\Controller\RatingController;
use App\Controller\RecipeController;
use App\Controller\SearchController;
use App\Controller\UserController;
use App\Core\Auth;
use App\Core\Request;
use App\Core\Response;
use App\Core\Router;
use App\Core\Session;
use App\Service\BackupService;
use App\Service\EmailService;
use App\Service\ImageService;
use App\Service\ScalerService;
use App\Service\SearchService;
use App\Service\WhatCanIMakeService;
use App\Store\CookbookStore;
use App\Store\IndexBuilder;
use App\Store\IngredientDictionary;
use App\Store\RatingsStore;
use App\Store\RecipeStore;
use App\Store\UserStore;

$request = Request::fromGlobals();
$session = new Session();
$userStore = new UserStore();
$auth = new Auth($session, $userStore);
$recipeStore = new RecipeStore();
$ratingsStore = new RatingsStore($recipeStore);
$cookbookStore = new CookbookStore();
$dictionary = new IngredientDictionary();
$indexBuilder = new IndexBuilder($recipeStore);
$imageService = new ImageService();
$emailService = new EmailService();
$searchService = new SearchService($indexBuilder, $recipeStore);
$scalerService = new ScalerService();
$whatCanIMake = new WhatCanIMakeService($recipeStore);
$backupService = new BackupService();

$homeController = new HomeController($recipeStore, $indexBuilder, $auth);
$authController = new AuthController($userStore, $auth, $session, $emailService);
$recipeController = new RecipeController($recipeStore, $auth, $session, $ratingsStore, $dictionary, $indexBuilder, $imageService, $emailService, $userStore);
$searchController = new SearchController($searchService, $whatCanIMake, $dictionary, $auth, $indexBuilder);
$ratingController = new RatingController($ratingsStore, $recipeStore, $auth);
$cookbookController = new CookbookController($cookbookStore, $recipeStore, $auth, $session, $scalerService);
$moderationController = new ModerationController($recipeStore, $userStore, $session, $auth, $emailService);
$adminController = new AdminController($userStore, $recipeStore, $ratingsStore, $indexBuilder, $session, $backupService, $auth);
$userController = new UserController($userStore, $recipeStore, $auth, $session, $imageService, $emailService);

$router = new Router($auth);
$router->get('/', [$homeController, 'index']);
$router->get('/register', [$authController, 'showRegister']);
$router->post('/register', [$authController, 'handleRegister']);
$router->get('/login', [$authController, 'showLogin']);
$router->post('/login', [$authController, 'handleLogin']);
$router->get('/logout', [$authController, 'handleLogout'], ['auth']);
$router->get('/verify-email', [$authController, 'handleVerifyEmail']);
$router->get('/reset-password', [$authController, 'showResetRequest']);
$router->post('/reset-password', [$authController, 'handleResetRequest']);
$router->get('/reset-password/confirm', [$authController, 'showResetConfirm']);
$router->post('/reset-password/confirm', [$authController, 'handleResetConfirm']);
$router->get('/recipes', [$recipeController, 'list']);
$router->get('/recipes/create', [$recipeController, 'showCreate'], ['auth']);
$router->post('/recipes/create', [$recipeController, 'handleCreate'], ['auth']);
$router->get('/recipe/{id}', [$recipeController, 'show']);
$router->get('/recipe/{id}/edit', [$recipeController, 'showEdit'], ['auth']);
$router->post('/recipe/{id}/edit', [$recipeController, 'handleEdit'], ['auth']);
$router->post('/recipe/{id}/delete', [$recipeController, 'softDelete'], ['auth']);
$router->post('/recipe/{id}/restore', [$recipeController, 'restore'], ['role:editor']);
$router->post('/recipe/{id}/purge', [$recipeController, 'hardDelete'], ['role:admin']);
$router->get('/recipe/{id}/print', [$recipeController, 'printView']);
$router->post('/recipe/{id}/flag', [$recipeController, 'flag'], ['auth']);
$router->get('/search', [$searchController, 'results']);
$router->get('/what-can-i-make', [$searchController, 'form']);
$router->post('/what-can-i-make', [$searchController, 'match']);
$router->get('/api/ingredients', [$searchController, 'apiIngredients']);
$router->post('/recipe/{id}/rate', [$ratingController, 'rate'], ['auth']);
$router->get('/cookbooks', [$cookbookController, 'list'], ['auth']);
$router->get('/cookbooks/create', [$cookbookController, 'showCreate'], ['auth']);
$router->post('/cookbooks/create', [$cookbookController, 'handleCreate'], ['auth']);
$router->get('/cookbook/{id}', [$cookbookController, 'show'], ['auth']);
$router->get('/cookbook/{id}/edit', [$cookbookController, 'showEdit'], ['auth']);
$router->post('/cookbook/{id}/edit', [$cookbookController, 'handleEdit'], ['auth']);
$router->post('/cookbook/{id}/delete', [$cookbookController, 'delete'], ['auth']);
$router->post('/cookbook/{id}/share', [$cookbookController, 'generateShareToken'], ['auth']);
$router->get('/cookbook/shared/{token}', [$cookbookController, 'showShared']);
$router->get('/moderation', [$moderationController, 'queue'], ['role:editor']);
$router->post('/moderation/resolve', [$moderationController, 'resolve'], ['role:editor']);
$router->get('/admin', [$adminController, 'dashboard'], ['role:admin']);
$router->get('/admin/users', [$adminController, 'users'], ['role:admin']);
$router->post('/admin/users/{id}/role', [$adminController, 'changeRole'], ['role:admin']);
$router->post('/admin/users/{id}/suspend', [$adminController, 'suspend'], ['role:admin']);
$router->post('/admin/users/{id}/purge', [$adminController, 'purgeUser'], ['role:admin']);
$router->get('/admin/config', [$adminController, 'showConfig'], ['role:admin']);
$router->post('/admin/config', [$adminController, 'saveConfig'], ['role:admin']);
$router->post('/admin/backup', [$adminController, 'createBackup'], ['role:admin']);
$router->get('/admin/backups', [$adminController, 'backups'], ['role:admin']);
$router->post('/admin/rebuild-index', [$adminController, 'rebuildIndexes'], ['role:admin']);
$router->get('/user/{username}', [$userController, 'profile']);
$router->get('/settings', [$userController, 'showSettings'], ['auth']);
$router->post('/settings', [$userController, 'saveSettings'], ['auth']);
$router->post('/settings/avatar', [$userController, 'uploadAvatar'], ['auth']);
$router->setNotFoundHandler(static function () use ($auth): Response {
    return new Response(render('home/index', ['auth' => $auth, 'featured' => [], 'categoryCounts' => [], 'headline' => 'Page not found', 'message' => 'The page you requested could not be found.']), 404);
});
$router->dispatch($request)->send();
