<?php
declare(strict_types=1);
namespace App\Controller;
use App\Core\Auth; use App\Core\Request; use App\Core\Response; use App\Core\Session; use App\Service\BackupService; use App\Store\FlagsStore; use App\Store\IndexBuilder; use App\Store\RatingsStore; use App\Store\RecipeStore; use App\Store\UserStore; use App\Util\Csrf;
final class AdminController
{
    private FlagsStore $flagsStore;
    public function __construct(private UserStore $userStore, private RecipeStore $recipeStore, private RatingsStore $ratingsStore, private IndexBuilder $indexBuilder, private Session $session, private BackupService $backupService, private Auth $auth) { $this->flagsStore = new FlagsStore(); }
    public function dashboard(Request $request): Response { return new Response(render('admin/dashboard', ['auth' => $this->auth, 'stats' => ['recipes' => $this->recipeStore->countAll(), 'users' => count($this->userStore->all()), 'ratings' => $this->ratingsStore->totalRatings(), 'flags' => $this->flagsStore->activeFlagCount()]], 'layout/admin')); }
    public function users(Request $request): Response { $page = max(1, (int) $request->query('page', 1)); $listing = $this->userStore->list($page, 15); return new Response(render('admin/users', ['auth' => $this->auth, 'listing' => $listing], 'layout/admin')); }
    public function changeRole(Request $request, string $id): Response { if (Csrf::validateToken((string) $request->post('csrf_token', ''))) { $role = (string) $request->post('role', 'user'); if (in_array($role, ['user', 'editor', 'admin'], true)) { $this->userStore->update($id, ['role' => $role]); flash('success', 'User role updated.'); } } return Response::redirect('/admin/users'); }
    public function suspend(Request $request, string $id): Response { if (Csrf::validateToken((string) $request->post('csrf_token', ''))) { $this->userStore->softDelete($id); flash('success', 'User suspended.'); } return Response::redirect('/admin/users'); }
    public function purgeUser(Request $request, string $id): Response { if (Csrf::validateToken((string) $request->post('csrf_token', ''))) { $this->userStore->hardDelete($id); flash('success', 'User permanently deleted.'); } return Response::redirect('/admin/users'); }
    public function showConfig(Request $request): Response { return new Response(render('admin/config', ['auth' => $this->auth, 'config' => site_config()], 'layout/admin')); }
    public function saveConfig(Request $request): Response { if (Csrf::validateToken((string) $request->post('csrf_token', ''))) { $config = site_config(); foreach (['site_name', 'tagline', 'hcaptcha_site_key', 'hcaptcha_secret', 'smtp_host', 'smtp_port', 'smtp_user', 'smtp_pass', 'from_email', 'from_name', 'default_theme', 'items_per_page'] as $field) if ($request->post($field) !== null) $config[$field] = $field === 'smtp_port' || $field === 'items_per_page' ? (int) $request->post($field) : (string) $request->post($field); save_site_config($config); flash('success', 'Configuration saved.'); } return Response::redirect('/admin/config'); }
    public function createBackup(Request $request): Response { if (Csrf::validateToken((string) $request->post('csrf_token', ''))) { try { $this->backupService->createBackup(); flash('success', 'Backup created successfully.'); } catch (\Throwable $exception) { flash('error', $exception->getMessage()); } } return Response::redirect('/admin/backups'); }
    public function backups(Request $request): Response { return new Response(render('admin/backup', ['auth' => $this->auth, 'backups' => $this->backupService->listBackups()], 'layout/admin')); }
    public function rebuildIndexes(Request $request): Response { if (Csrf::validateToken((string) $request->post('csrf_token', ''))) { $this->indexBuilder->rebuild(); flash('success', 'Indexes rebuilt.'); } return Response::redirect('/admin'); }
}
