<?php
declare(strict_types=1);
namespace App\Controller;
use App\Core\Auth; use App\Core\Request; use App\Core\Response; use App\Core\Session; use App\Service\ScalerService; use App\Store\CookbookStore; use App\Store\RecipeStore; use App\Util\Csrf; use App\Util\Token; use App\Util\Uuid;
final class CookbookController
{
    public function __construct(private CookbookStore $cookbookStore, private RecipeStore $recipeStore, private Auth $auth, private Session $session, private ScalerService $scalerService) {}
    public function list(Request $request): Response { $user = $this->auth->getCurrentUser(); return new Response(render('cookbook/index', ['auth' => $this->auth, 'cookbooks' => $this->cookbookStore->list($user['id'])])); }
    public function showCreate(Request $request): Response { return new Response(render('cookbook/edit', ['auth' => $this->auth, 'cookbook' => ['title' => '', 'description' => '', 'sections' => []], 'recipes' => $this->recipeStore->listPublished(1, 200, 'latest')['items'], 'formAction' => '/cookbooks/create', 'isCreate' => true])); }
    public function handleCreate(Request $request): Response { $user = $this->auth->getCurrentUser(); if (!Csrf::validateToken((string) $request->post('csrf_token', ''))) { flash('error', 'Your session expired.'); return Response::redirect('/cookbooks/create'); } $cookbook = $this->cookbookStore->create($user['id'], $this->extractCookbook($request)); flash('success', 'Cookbook created.'); return Response::redirect('/cookbook/' . $cookbook['id']); }
    public function show(Request $request, string $id): Response { $user = $this->auth->getCurrentUser(); $cookbook = $this->cookbookStore->findById($user['id'], $id); if ($cookbook === null) { flash('error', 'Cookbook not found.'); return Response::redirect('/cookbooks'); } return new Response(render('cookbook/show', ['auth' => $this->auth, 'cookbook' => $this->expandCookbook($cookbook)])); }
    public function showEdit(Request $request, string $id): Response { $user = $this->auth->getCurrentUser(); $cookbook = $this->cookbookStore->findById($user['id'], $id); if ($cookbook === null) { flash('error', 'Cookbook not found.'); return Response::redirect('/cookbooks'); } return new Response(render('cookbook/edit', ['auth' => $this->auth, 'cookbook' => $cookbook, 'recipes' => $this->recipeStore->listPublished(1, 200, 'latest')['items'], 'formAction' => '/cookbook/' . $id . '/edit', 'isCreate' => false])); }
    public function handleEdit(Request $request, string $id): Response { $user = $this->auth->getCurrentUser(); if (!Csrf::validateToken((string) $request->post('csrf_token', ''))) { flash('error', 'Your session expired.'); return Response::redirect('/cookbook/' . $id . '/edit'); } $this->cookbookStore->update($user['id'], $id, $this->extractCookbook($request)); flash('success', 'Cookbook updated.'); return Response::redirect('/cookbook/' . $id); }
    public function delete(Request $request, string $id): Response { $user = $this->auth->getCurrentUser(); if (Csrf::validateToken((string) $request->post('csrf_token', ''))) { $this->cookbookStore->delete($user['id'], $id); flash('success', 'Cookbook deleted.'); } return Response::redirect('/cookbooks'); }
    public function generateShareToken(Request $request, string $id): Response { $user = $this->auth->getCurrentUser(); if (Csrf::validateToken((string) $request->post('csrf_token', ''))) { $this->cookbookStore->update($user['id'], $id, ['share_token' => Token::generate(16)]); flash('success', 'Share link created.'); } return Response::redirect('/cookbook/' . $id); }
    public function showShared(Request $request, string $token): Response { $cookbook = $this->cookbookStore->findByShareToken($token); if ($cookbook === null) return new Response('Cookbook not found', 404); return new Response(render('cookbook/show', ['auth' => $this->auth, 'cookbook' => $this->expandCookbook($cookbook), 'shared' => true])); }
    private function extractCookbook(Request $request): array { $sections = []; foreach (($request->post('sections', []) ?: []) as $section) { $title = trim((string) ($section['title'] ?? '')); $recipes = []; foreach (($section['recipes'] ?? []) as $entry) { if (empty($entry['recipe_id'])) continue; $recipes[] = ['recipe_id' => (string) $entry['recipe_id'], 'scale' => (float) ($entry['scale'] ?? 1), 'notes' => trim((string) ($entry['notes'] ?? ''))]; } if ($title !== '' || $recipes !== []) $sections[] = ['id' => Uuid::generateV4(), 'title' => $title ?: 'Untitled Section', 'recipes' => $recipes]; } return ['title' => trim((string) $request->post('title', '')), 'description' => trim((string) $request->post('description', '')), 'sections' => $sections]; }
    private function expandCookbook(array $cookbook): array { foreach ($cookbook['sections'] as $sectionIndex => $section) foreach ($section['recipes'] as $recipeIndex => $entry) { $recipe = $this->recipeStore->findById((string) $entry['recipe_id']); if ($recipe === null || ($recipe['status'] ?? '') === 'blocked' || !empty($recipe['deleted_at'])) { $cookbook['sections'][$sectionIndex]['recipes'][$recipeIndex]['recipe'] = null; continue; } $cookbook['sections'][$sectionIndex]['recipes'][$recipeIndex]['recipe'] = $this->scalerService->scale($recipe, (float) ($entry['scale'] ?? 1)); } return $cookbook; }
}
