<?php
declare(strict_types=1);
namespace App\Controller;
use App\Core\Auth; use App\Core\Request; use App\Core\Response; use App\Core\Session; use App\Service\EmailService; use App\Store\RecipeStore; use App\Store\UserStore; use App\Util\Csrf;
final class ModerationController
{
    public function __construct(private RecipeStore $recipeStore, private UserStore $userStore, private Session $session, private Auth $auth, private EmailService $emailService) {}
    public function queue(Request $request): Response { $flags = array_values(array_filter(read_json_file(DATA_PATH . '/moderation/flags.json', []), static fn(array $flag): bool => !empty($flag['active']))); foreach ($flags as $index => $flag) { $flags[$index]['recipe'] = $this->recipeStore->findById((string) $flag['recipe_id']); $flags[$index]['reporter'] = $this->userStore->findById((string) $flag['user_id']); } return new Response(render('moderation/queue', ['auth' => $this->auth, 'flags' => $flags], 'layout/admin')); }
    public function resolve(Request $request): Response { if (!Csrf::validateToken((string) $request->post('csrf_token', ''))) { flash('error', 'Your session expired.'); return Response::redirect('/moderation'); } $flagId = (string) $request->post('flag_id', ''); $action = (string) $request->post('action', 'approve'); $flags = read_json_file(DATA_PATH . '/moderation/flags.json', []); foreach ($flags as &$flag) { if (($flag['id'] ?? '') !== $flagId) continue; $flag['active'] = false; $flag['resolved_at'] = current_timestamp(); $flag['resolution'] = $action; $recipeId = (string) $flag['recipe_id']; if ($action === 'approve') $this->recipeStore->update($recipeId, ['status' => 'published']); elseif ($action === 'block') $this->recipeStore->update($recipeId, ['status' => 'blocked']); elseif ($action === 'delete') $this->recipeStore->softDelete($recipeId); $recipe = $this->recipeStore->findById($recipeId); if ($recipe) { $owner = $this->userStore->findById((string) $recipe['author_id']); if ($owner) $this->emailService->sendModerationNotice($owner['email'], 'Moderation update for your recipe', 'A moderator reviewed your recipe and marked it as: ' . $action); } append_audit('moderation.resolve', ['flag_id' => $flagId, 'action' => $action]); break; } unset($flag); write_json_file(DATA_PATH . '/moderation/flags.json', $flags); flash('success', 'Flag resolved.'); return Response::redirect('/moderation'); }
}
