<?php
declare(strict_types=1);
namespace App\Controller;
use App\Core\Auth; use App\Core\Request; use App\Core\Response; use App\Core\Session; use App\Service\EmailService; use App\Service\ImageService; use App\Store\IndexBuilder; use App\Store\IngredientDictionary; use App\Store\RatingsStore; use App\Store\RecipeStore; use App\Store\UserStore; use App\Util\Csrf;
final class RecipeController
{
    public function __construct(private RecipeStore $recipeStore, private Auth $auth, private Session $session, private RatingsStore $ratingsStore, private IngredientDictionary $dictionary, private IndexBuilder $indexBuilder, private ImageService $imageService, private EmailService $emailService, private UserStore $userStore) {}
    public function list(Request $request): Response { $page = max(1, (int) $request->query('page', 1)); $sort = (string) $request->query('sort', 'latest'); $recipes = $this->recipeStore->listPublished($page, (int) site_config('items_per_page', 12), $sort); return new Response(render('recipe/list', ['auth' => $this->auth, 'recipes' => $recipes['items'], 'pagination' => $recipes, 'sort' => $sort])); }
    public function show(Request $request, string $id): Response { $recipe = $this->recipeStore->findById($id); if ($recipe === null || !empty($recipe['deleted_at'])) return new Response('Recipe not found', 404); $flagStatus = $this->getFlagStatus($id); $user = $this->auth->getCurrentUser(); $canViewBlocked = $user && (($user['id'] === $recipe['author_id']) || $this->auth->hasRole('editor')); if (($recipe['status'] ?? '') === 'blocked' && !$canViewBlocked) return new Response(render('recipe/show', ['auth' => $this->auth, 'recipe' => $recipe, 'author' => $this->userStore->findById((string) $recipe['author_id']), 'ratingStats' => $this->ratingsStore->getStats($id), 'userRating' => $user ? $this->ratingsStore->getUserRating($id, $user['id']) : null, 'flagStatus' => $flagStatus, 'blocked' => true, 'printMode' => false]), 403); return new Response(render('recipe/show', ['auth' => $this->auth, 'recipe' => $recipe, 'author' => $this->userStore->findById((string) $recipe['author_id']), 'ratingStats' => $this->ratingsStore->getStats($id), 'userRating' => $user ? $this->ratingsStore->getUserRating($id, $user['id']) : null, 'flagStatus' => $flagStatus, 'blocked' => false, 'printMode' => false])); }
    public function printView(Request $request, string $id): Response { $recipe = $this->recipeStore->findById($id); if ($recipe === null) return new Response('Recipe not found', 404); return new Response(render('recipe/show', ['auth' => $this->auth, 'recipe' => $recipe, 'author' => $this->userStore->findById((string) $recipe['author_id']), 'ratingStats' => $this->ratingsStore->getStats($id), 'userRating' => null, 'flagStatus' => $this->getFlagStatus($id), 'blocked' => false, 'printMode' => true])); }
    public function showCreate(Request $request): Response { return new Response(render('recipe/create', ['auth' => $this->auth, 'recipe' => $this->blankRecipe(), 'categories' => default_categories(), 'errors' => [], 'formAction' => '/recipes/create'])); }
    public function handleCreate(Request $request): Response { return $this->saveRecipe($request); }
    public function showEdit(Request $request, string $id): Response { $recipe = $this->recipeStore->findById($id); if ($recipe === null || !$this->canManageRecipe($recipe)) { flash('error', 'You do not have permission to edit that recipe.'); return Response::redirect('/recipes'); } return new Response(render('recipe/edit', ['auth' => $this->auth, 'recipe' => $recipe, 'categories' => default_categories(), 'errors' => [], 'formAction' => '/recipe/' . $id . '/edit'])); }
    public function handleEdit(Request $request, string $id): Response { return $this->saveRecipe($request, $id); }
    public function softDelete(Request $request, string $id): Response { if (!$this->verifyMutation($request)) return Response::redirect('/recipe/' . $id); $recipe = $this->recipeStore->findById($id); if ($recipe && $this->canManageRecipe($recipe)) { $this->recipeStore->softDelete($id); $this->indexBuilder->rebuild(); flash('success', 'Recipe deleted.'); } return Response::redirect('/recipes'); }
    public function restore(Request $request, string $id): Response { if ($this->verifyMutation($request)) { $this->recipeStore->restore($id); $this->indexBuilder->rebuild(); flash('success', 'Recipe restored.'); } return Response::redirect('/recipe/' . $id); }
    public function hardDelete(Request $request, string $id): Response { if ($this->verifyMutation($request)) { $recipe = $this->recipeStore->findById($id); if ($recipe) { foreach ($recipe['images'] ?? [] as $image) $this->imageService->delete((string) $image); $this->recipeStore->hardDelete($id); $this->indexBuilder->rebuild(); flash('success', 'Recipe permanently removed.'); } } return Response::redirect('/recipes'); }
    public function flag(Request $request, string $id): Response { if (!$this->verifyMutation($request)) return Response::redirect('/recipe/' . $id); $recipe = $this->recipeStore->findById($id); $user = $this->auth->getCurrentUser(); if ($recipe === null || $user === null) return Response::redirect('/recipes'); $reason = trim((string) $request->post('reason', '')); $details = trim((string) $request->post('details', '')); $allowed = ['copyright', 'spam', 'unsafe', 'offensive', 'other']; if (!in_array($reason, $allowed, true)) { flash('error', 'Please choose a valid flag reason.'); return Response::redirect('/recipe/' . $id); } $flags = read_json_file(DATA_PATH . '/moderation/flags.json', []); foreach ($flags as $flag) if (($flag['recipe_id'] ?? '') === $id && ($flag['user_id'] ?? '') === $user['id'] && !empty($flag['active'])) { flash('info', 'You already flagged this recipe.'); return Response::redirect('/recipe/' . $id); } $flags[] = ['id' => bin2hex(random_bytes(8)), 'recipe_id' => $id, 'user_id' => $user['id'], 'reason' => $reason, 'details' => $details, 'active' => true, 'created_at' => current_timestamp()]; write_json_file(DATA_PATH . '/moderation/flags.json', $flags); $status = $this->getFlagStatus($id); if (($status['active_count'] ?? 0) >= 2) $this->recipeStore->update($id, ['status' => 'blocked']); $owner = $this->userStore->findById((string) $recipe['author_id']); if ($owner) $this->emailService->sendModerationNotice($owner['email'], 'Your recipe was flagged', 'A recipe you published has been flagged and sent for review.'); append_audit('recipe.flagged', ['recipe_id' => $id, 'user_id' => $user['id'], 'reason' => $reason]); flash('success', 'Thanks — your flag has been submitted.'); return Response::redirect('/recipe/' . $id); }
    private function saveRecipe(Request $request, ?string $id = null): Response
    {
        $data = $request->postData(); $existing = $id ? $this->recipeStore->findById($id) : null; if (!Csrf::validateToken((string) ($data['csrf_token'] ?? ''))) { flash('error', 'Your session expired.'); return Response::redirect($id ? '/recipe/' . $id . '/edit' : '/recipes/create'); } if ($existing && !$this->canManageRecipe($existing)) { flash('error', 'You do not have permission to edit that recipe.'); return Response::redirect('/recipes'); }
        $recipe = $this->buildRecipePayload($data, $existing); $errors = $this->validateRecipe($recipe); if ($errors !== []) return new Response(render($id ? 'recipe/edit' : 'recipe/create', ['auth' => $this->auth, 'recipe' => array_merge($existing ?? $this->blankRecipe(), $recipe), 'categories' => default_categories(), 'errors' => $errors, 'formAction' => $id ? '/recipe/' . $id . '/edit' : '/recipes/create']), 422);
        $saved = $existing ? $this->recipeStore->update($id, $recipe) : $this->recipeStore->create(array_merge($recipe, ['author_id' => $this->auth->getCurrentUser()['id']]));
        $uploads = $request->file('images'); if (is_array($uploads) && isset($uploads['name']) && is_array($uploads['name'])) { foreach ($this->normalizeFilesArray($uploads) as $file) { if (($file['error'] ?? UPLOAD_ERR_NO_FILE) === UPLOAD_ERR_NO_FILE) continue; $saved['images'][] = $this->imageService->upload($file, $saved['id']); } $saved = $this->recipeStore->update($saved['id'], ['images' => array_values(array_unique($saved['images']))]); }
        $this->indexBuilder->rebuild(); flash('success', 'Recipe saved successfully.'); return Response::redirect('/recipe/' . $saved['id']);
    }
    private function buildRecipePayload(array $data, ?array $existing = null): array
    {
        $tags = array_values(array_filter(array_map('trim', explode(',', (string) ($data['tags'] ?? ''))))); $categories = array_values(array_filter(array_map('trim', explode(',', (string) ($data['categories'] ?? ''))))); $ingredients = []; foreach (($data['ingredient_name'] ?? []) as $index => $name) { $name = trim((string) $name); if ($name === '') continue; $canonical = $this->dictionary->findByName($name) ?? $this->dictionary->add(['name' => $name, 'aliases' => [], 'category' => 'unverified', 'created_by' => $this->auth->getCurrentUser()['id'] ?? null]); $ingredients[] = ['ingredient_id' => $canonical['id'], 'name' => $canonical['name'], 'quantity' => (($data['ingredient_quantity'][$index] ?? '') === '' ? null : (float) $data['ingredient_quantity'][$index]), 'unit' => trim((string) ($data['ingredient_unit'][$index] ?? '')), 'system' => in_array(strtolower((string) ($data['ingredient_unit'][$index] ?? '')), ['ml', 'l', 'g', 'kg'], true) ? 'metric' : 'us', 'preparation' => trim((string) ($data['ingredient_preparation'][$index] ?? ''))]; }
        $steps = array_values(array_filter(array_map(static fn(mixed $step): string => trim((string) $step), $data['steps'] ?? [])));
        return ['title' => trim((string) ($data['title'] ?? '')), 'slug' => slugify((string) ($data['title'] ?? '')), 'description' => trim((string) ($data['description'] ?? '')), 'servings' => max(1, (int) ($data['servings'] ?? 1)), 'yield_amount' => ($data['yield_amount'] ?? '') === '' ? null : (float) $data['yield_amount'], 'yield_unit' => trim((string) ($data['yield_unit'] ?? '')) ?: null, 'ingredients' => $ingredients, 'steps' => $steps, 'tags' => array_values(array_unique($tags)), 'categories' => array_values(array_unique($categories)), 'status' => in_array(($data['status'] ?? 'draft'), ['draft', 'published', 'blocked'], true) ? (string) $data['status'] : 'draft', 'deleted_at' => $existing['deleted_at'] ?? null];
    }
    private function validateRecipe(array $recipe): array { $errors = []; if ($recipe['title'] === '') $errors['title'][] = 'Title is required.'; if ($recipe['description'] === '') $errors['description'][] = 'Description is required.'; if ($recipe['status'] === 'published') { if ($recipe['categories'] === []) $errors['categories'][] = 'At least one category is required to publish.'; if ($recipe['ingredients'] === []) $errors['ingredients'][] = 'Add at least one ingredient.'; if ($recipe['steps'] === []) $errors['steps'][] = 'Add at least one step.'; } return $errors; }
    private function canManageRecipe(array $recipe): bool { $user = $this->auth->getCurrentUser(); return $user !== null && ($user['id'] === $recipe['author_id'] || $this->auth->hasRole('editor')); }
    private function verifyMutation(Request $request): bool { return Csrf::validateToken((string) $request->post('csrf_token', '')); }
    private function normalizeFilesArray(array $files): array { $normalized = []; foreach (($files['name'] ?? []) as $index => $name) $normalized[] = ['name' => $name, 'type' => $files['type'][$index] ?? '', 'tmp_name' => $files['tmp_name'][$index] ?? '', 'error' => $files['error'][$index] ?? UPLOAD_ERR_NO_FILE, 'size' => $files['size'][$index] ?? 0]; return $normalized; }
    private function blankRecipe(): array { return ['title' => '', 'description' => '', 'servings' => 4, 'yield_amount' => null, 'yield_unit' => '', 'ingredients' => [['name' => '', 'quantity' => '', 'unit' => '', 'preparation' => '']], 'steps' => [''], 'tags' => [], 'categories' => [], 'images' => [], 'status' => 'draft']; }
    private function getFlagStatus(string $recipeId): array { $flags = array_values(array_filter(read_json_file(DATA_PATH . '/moderation/flags.json', []), static fn(array $flag): bool => ($flag['recipe_id'] ?? '') === $recipeId && !empty($flag['active']))); return ['active_count' => count($flags), 'flags' => $flags]; }
}
