<?php
declare(strict_types=1);
namespace App\Controller;
use App\Core\Auth; use App\Core\Request; use App\Core\Response; use App\Core\Session; use App\Service\EmailService; use App\Service\ImageService; use App\Store\RecipeStore; use App\Store\UserStore; use App\Util\Csrf; use App\Util\Token;
final class UserController
{
    public function __construct(private UserStore $userStore, private RecipeStore $recipeStore, private Auth $auth, private Session $session, private ImageService $imageService, private EmailService $emailService) {}
    public function profile(Request $request, string $username): Response { $user = $this->userStore->findByUsername($username); if ($user === null || !empty($user['deleted_at'])) return new Response('User not found', 404); $recipes = array_values(array_filter($this->recipeStore->listByAuthor($user['id']), static fn(array $recipe): bool => ($recipe['status'] ?? '') === 'published' && empty($recipe['deleted_at']))); return new Response(render('user/profile', ['auth' => $this->auth, 'profileUser' => $user, 'recipes' => $recipes, 'isSettings' => false])); }
    public function showSettings(Request $request): Response { return new Response(render('user/profile', ['auth' => $this->auth, 'profileUser' => $this->auth->getCurrentUser(), 'recipes' => $this->recipeStore->listByAuthor($this->auth->getCurrentUser()['id']), 'isSettings' => true])); }
    public function saveSettings(Request $request): Response { $user = $this->auth->getCurrentUser(); if ($user === null) return Response::redirect('/login'); if (!Csrf::validateToken((string) $request->post('csrf_token', ''))) return $request->expectsJson() ? Response::json(['error' => 'Invalid CSRF token'], 422) : Response::redirect('/settings'); $updates = ['display_name' => trim((string) $request->post('display_name', $user['display_name'] ?? '')), 'bio' => trim((string) $request->post('bio', $user['bio'] ?? '')), 'theme' => (string) $request->post('theme', $user['theme'] ?? site_config('default_theme', 'light'))]; $username = trim((string) $request->post('username', $user['username'])); if ($username !== $user['username']) { $existing = $this->userStore->findByUsername($username); if ($existing === null) $updates['username'] = $username; } $email = strtolower(trim((string) $request->post('email', $user['email']))); if ($email !== $user['email'] && filter_var($email, FILTER_VALIDATE_EMAIL)) { $token = Token::generate(); $updates['email'] = $email; $updates['verified'] = false; $updates['verify_token'] = $token; $this->emailService->sendVerification($email, $token); } $this->userStore->update($user['id'], $updates); if ($request->expectsJson() || $request->post('theme_only')) return Response::json(['ok' => true]); flash('success', 'Settings saved.'); return Response::redirect('/settings'); }
    public function uploadAvatar(Request $request): Response { $user = $this->auth->getCurrentUser(); if ($user === null) return Response::redirect('/login'); if (!Csrf::validateToken((string) $request->post('csrf_token', ''))) { flash('error', 'Your session expired.'); return Response::redirect('/settings'); } $file = $request->file('avatar'); if (!is_array($file) || ($file['error'] ?? UPLOAD_ERR_NO_FILE) === UPLOAD_ERR_NO_FILE) { flash('error', 'Please choose an image to upload.'); return Response::redirect('/settings'); } $filename = $this->imageService->upload($file, 'avatar-' . $user['id']); $this->userStore->update($user['id'], ['avatar' => $filename]); flash('success', 'Avatar updated.'); return Response::redirect('/settings'); }
}
